// Package export renders the SKILL.md wrapper for one indexed block (docs/FORMAT.md, "Export").
package export

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/caveman-ai/blocks/internal/blockfile"
)

// Marker is the line that identifies a generated SKILL.md, so sync removes only files it wrote.
const Marker = "<!-- generated by caveman-blocks export; edit the block, then run caveman-blocks sync -->"

// Dirs are the skill directories export writes, relative to the repo root.
var Dirs = []string{".claude/skills", ".agents/skills"}

// Skill renders .../<name>/SKILL.md for b: frontmatter name and description (the summary), then the
// parameter table, the enforced call and the unenforced python3 fallback.
func Skill(b *blockfile.Block) []byte {
	h := b.Header
	call := blockfile.CallHint(b)
	direct := "python3 .blocks/" + h.Name + ".py" + strings.TrimPrefix(call, "caveman-blocks run "+h.Name)

	var s strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&s, format, a...) }
	w("---\nname: %s\ndescription: %s\n---\n%s\n\n# %s\n\n%s\n\n", h.Name, strconv.Quote(h.Summary), Marker, h.Name, h.Summary)
	if len(h.Params) > 0 {
		w("| Param | Type | Required | Default | Help |\n|---|---|---|---|---|\n")
		for _, p := range h.Params {
			req, def := "no", ""
			if p.Required {
				req = "yes"
			} else if p.Default != nil {
				def = fmt.Sprint(p.Default)
				if def == "" {
					def = `""`
				}
				def = "`" + def + "`"
			}
			typ := p.Type
			if p.Type == "enum" {
				typ = "enum: " + strings.Join(p.Values, ", ")
			}
			w("| `--%s` | %s | %s | %s | %s |\n", p.Name, cell(typ), req, cell(def), cell(p.Help))
		}
		w("\n")
	}
	w("Run it from the repo root:\n\n```\n%s\n```\n\n", call)
	w("It prints one JSON object with the keys %s.\n\n", strings.Join(h.Returns.Keys, ", "))
	w("Without the CLI, `%s` runs the same file, but nothing is enforced: no effects gate, no path confinement, no output cap.\n", direct)
	return []byte(s.String())
}

func cell(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", `\|`), "\n", " ")
}
